# Generated by Django 4.0.2 on 2022-04-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_buyer_user_status_seller_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='image',
        ),
    ]
