# Generated by Django 4.0.2 on 2022-04-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_shopproduct_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShopUser',
        ),
    ]
