# Generated by Django 4.0 on 2023-03-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_buyer_pic_alter_seller_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='home.buyer'),
            preserve_default=False,
        ),
    ]
